<?php
/**
 * @var \Magezon\PageBuilder\Block\Element\ContentSlider $block
 * @var \Magezon\PageBuilder\ViewModel\ContentSlider $viewModel
 */
$viewModel = $block->getViewModel();

$element         = $viewModel->getElement();
$title           = $viewModel->filter($element->getData('title'));
$titleAlign      = $element->getData('title_align');
$titleTag        = $element->getData('title_tag') ? $element->getData('title_tag') : 'h2';
$description     = $viewModel->filter($element->getData('description'));
$showLine        = $element->getData('show_line');
$linePosition    = $element->getData('line_position');
$items           = $block->toObjectArray($element->getItems());
$htmlId          = $element->getHtmlId();
$carouselOptions = $block->getOwlCarouselOptions();
$classes         = $block->getOwlCarouselClasses();
?>
<?php if (count($items)) { ?>
<div class="mgz-block">
        <?php if ($title || $description) { ?>
        <div class="mgz-block-heading mgz-block-heading-align-<?= $titleAlign ?><?= $showLine ? ' mgz-block-heading-line' : '' ?> mgz-block-heading-line-position-<?= $linePosition ?>">
                <?php if ($title) { ?>
                        <<?= $titleTag ?> class="title"><?= $title ?></<?= $titleTag ?>>
                <?php } ?>
                <?php if ($description) { ?>
                        <div class="info"><?= $description ?></div>
                <?php } ?>
        </div>
        <?php } ?>
        <div class="mgz-block-content">
                <?php if ($items && count($items)) { ?>
                        <div class="mgz-carousel owl-carousel <?= implode(' ', $classes) ?>" data-mage-init='{"Magezon_Builder/js/carousel":<?= $viewModel->getSerializedOptions($carouselOptions) ?>}'>
                                <?php foreach ($items as $item) { ?>
                                        <div class="mgz-content-carouse-slide">
                                                <?= $viewModel->filter($item['content']) ?>
                                        </div>
                                <?php } ?>
                        </div>
                <?php } ?>
        </div>
</div>
<?php } ?>
