<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magezon\PageBuilder\ViewModel\Flickr $viewModel */
$viewModel = $block->getViewModel();

$element     = $viewModel->getElement();
$title       = $viewModel->getFilteredTitle();
$titleAlign  = $element->getData('title_align');
$titleTag    = $viewModel->getTitleTag();
$description = $viewModel->getFilteredDescription();
$showLine    = $viewModel->isShowLine();
$options     = $viewModel->getSerializedOptions();
$xl          = $element->getData('item_xl');
$lg          = $element->getData('item_lg');
$md          = $element->getData('item_md');
$sm          = $element->getData('item_sm');
$xs          = $element->getData('item_xs');
?>
<div class="mgz-block">
	<?php if ($title || $description) { ?>
	<div class="mgz-block-heading mgz-block-heading-align-<?= $titleAlign ?><?= $showLine ? ' mgz-block-heading-line' : '' ?>">
		<?php if ($title) { ?>
			<<?= $titleTag ?> class="title"><?= $title ?></<?= $titleTag ?>>
		<?php } ?>
		<?php if ($description) { ?>
			<div class="info"><?= $description ?></div>
		<?php } ?>
	</div>
	<?php } ?>
        <div class="mgz-block-content">
                <div class="mgz-flick" data-mage-init='{"Magezon_PageBuilder/js/flickr":<?= $options ?>}'>
			<div class="spinner-wrapper">
                <div class="spinner"></div>
            </div>
			<div class="gallery-container mgz-grid-col-xl-<?= $xl ?> mgz-grid-col-lg-<?= $lg ?> mgz-grid-col-md-<?= $md ?> mgz-grid-col-sm-<?= $sm ?> mgz-grid-col-xs-<?= $xs ?>"></div>
		</div>
	</div>
</div>
